version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gin-mysql-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gin_mysql_api
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - gin-api-network

  redis:
    image: redis:7-alpine
    container_name: gin-mysql-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gin-api-network

  prometheus:
    image: prom/prometheus:latest
    container_name: gin-mysql-api-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - gin-api-network

volumes:
  mysql_data:
  redis_data:
  prometheus_data:

networks:
  gin-api-network:
    driver: bridge