# 简化的本地开发环境配置
# 使用简单的数据库配置，便于快速启动

server:
  host: "0.0.0.0"          # 服务监听地址
  port: 1800               # 服务端口
  mode: "debug"            # 运行模式: debug, release, test

database:
  host: "localhost"        # 数据库地址
  port: 3306              # 数据库端口
  username: "root"         # 数据库用户名
  password: ""             # 数据库密码 (本地开发环境)
  dbname: "hajimi"         # 数据库名
  charset: "utf8mb4"       # 字符集
  parseTime: true          # 解析时间
  loc: "Local"            # 时区
  maxIdleConns: 10        # 最大空闲连接数
  maxOpenConns: 100       # 最大打开连接数
  connMaxLifetime: 3600   # 连接最大生存时间(秒)

redis:
  host: "localhost"        # Redis地址
  port: 6379              # Redis端口
  password: ""            # Redis密码
  db: 0                   # Redis数据库编号
  poolSize: 10            # 连接池大小

jwt:
  secret: "hajimi-dev-secret"  # JWT密钥 (开发环境)
  expiration: 24          # Token过期时间(小时)

upload:
  maxSize: 100            # 最大上传文件大小(MB)
  allowedTypes: ["jpg", "jpeg", "png", "gif", "mp4", "avi", "mov"]  # 允许的文件类型
  uploadPath: "./uploads" # 上传文件存储路径

logging:
  level: "debug"          # 日志级别: debug, info, warn, error
  format: "text"          # 日志格式: json, text
  output: "stdout"        # 日志输出: stdout, file
  filename: "logs/app.log" # 日志文件路径

prometheus:
  enabled: false          # 是否启用Prometheus监控
  path: "/metrics"        # 监控指标路径
  port: 9093             # 监控服务端口
