global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hajimi-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # 应用程序监控
  - job_name: 'hajimi-api'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus metrics endpoint
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # 应用程序健康检查
  - job_name: 'hajimi-health'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s

  # MySQL 监控 (如果使用 mysqld_exporter)
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis 监控 (如果使用 redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter 系统监控
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s
    scrape_timeout: 10s